#!/bin/bash

read -r -d '' TEMPLATES << EOM
- cli (a function callable from the terminal)
- service-get (HTTP service, GET REQUEST)
- service-post (HTTP service, POST request)
EOM

echo "${TEMPLATES}" 

