#!/bin/bash
function_name=$1

mkdir ${function_name}
cd ${function_name}

read -r -d '' SOURCE << EOM
package main

import (
	hf "github.com/bots-garden/capsule/capsulemodule/hostfunctions"
)

func main() {
	hf.SetHandleHttp(Handle)
}

func Handle(req hf.Request) (resp hf.Response, errResp error) {

	hf.Log("📝 Body: " + request.Body)
	hf.Log("📝 URI: " + request.Uri)
	hf.Log("📝 Method: " + request.Method)

	headers := map[string]string{
		"Content-Type": "text/plain; charset=utf-8",
	}

	resp = hf.Response{
		Body: "👋 hello " + request.Body,
		Headers: headers,
	}

	return resp , nil
}
EOM

echo "${SOURCE}" >> "${function_name}.go"

read -r -d '' MODULE << EOM
module ${function_name}

go 1.18
EOM

echo "${MODULE}" >> go.mod

